'use strict';
const $=id=>document.getElementById(id);let before=null;
function message(s){$('message').textContent=s;}
function row(parent,text){const el=document.createElement('div');el.className='row';el.textContent=text;parent.appendChild(el);return el;}
function button(parent,label,action){const b=document.createElement('button');b.textContent=label;b.onclick=()=>Promise.resolve().then(action).catch(e=>message(e.message));parent.appendChild(b);return b;}
async function watchAction(action,id){const r=await chrome.runtime.sendMessage({action,id});if(r?.error)throw Error(r.error);await renderWatch();}
async function renderWatch(){const s=await lookSettings(),d=await chrome.storage.local.get(['urlWatchStatus','urlWatchLast','urlMachines','urlWarning','urlCheckedAt','urlQueue']);
 $('enabled').checked=s.urlWatchEnabled;$('status').textContent=(d.urlWatchStatus||'Paused.')+(d.urlCheckedAt?' Last check: '+new Date(d.urlCheckedAt).toLocaleString():'');$('warning').textContent=d.urlWarning||'';
 $('last').textContent=d.urlWatchLast?'Last opened: '+d.urlWatchLast.url:'';$('machines').replaceChildren();
 for(const m of d.urlMachines||[])row($('machines'),m.machine+': '+(m.error||((Date.now()/1000-m.checked)>90?'STALE':m.panes+' panes; '+(m.sockets||[]).length+' sockets'))+(m.warnings?.length?' — History warning '+(m.warningsAt?new Date(m.warningsAt*1000).toLocaleString()+': ':'')+m.warnings.join('; '):''));
 $('queue').replaceChildren();const history=(d.urlQueue||[]).filter(e=>e.hub===s.hubUrl);const visible=[...history.filter(e=>e.state==='queued'),...history.filter(e=>e.state!=='queued').slice(-100).reverse()];for(const e of visible){const el=row($('queue'),e.state+' · '+e.machine+' / '+e.session+' · '+e.url);button(el,'Open again',()=>watchAction('open',e.id));if(e.state==='queued')button(el,'Dismiss',()=>watchAction('dismiss',e.id));}
}
async function drafts(){const s=await lookSettings();await captureDB.prune(s.draftRetentionDays);const data=await captureDB.list();$('drafts').replaceChildren();$('local-usage').textContent=data.length+' drafts; approximately '+(JSON.stringify(data).length/1048576).toFixed(1)+' MiB';
 for(const c of data.sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt))){const el=row($('drafts'),(c.uploadId?'Saved #'+c.uploadId:'Unsent')+' · '+(c.project||'No project')+' · '+c.title+' · '+new Date(c.capturedAt).toLocaleString());button(el,'Reopen',()=>chrome.tabs.create({url:chrome.runtime.getURL('editor.html')+'?id='+c.id}));button(el,'Delete local draft',async()=>{if(confirm('Delete this local draft?')){await captureDB.remove(c.id);await drafts();}});}
}
async function captures(append=false){const data=await lookFetch('/api/look-here/captures?limit=20'+(append&&before?'&before='+before:''));if(!append)$('captures').replaceChildren();$('usage').textContent=data.count+' saved marks; '+(data.bytes/1048576).toFixed(1)+' MiB';$('capture-days').value=data.retentionDays;
 for(const c of data.captures){const el=row($('captures'),'#'+c.id+' · '+(c.project||'No project')+' / '+(c.thread||'No task')+' · '+(c.note||'')+' · '+(c.reviewed_at?'Reviewed '+new Date(c.reviewed_at*1000).toLocaleString():'Not marked reviewed'));button(el,'View',()=>chrome.tabs.create({url:chrome.runtime.getURL('viewer.html')+'?id='+c.id}));button(el,'Delete saved mark',async()=>{if(confirm('Permanently delete saved mark #'+c.id+' from the hub?')){await lookFetch('/api/look-here/captures/'+c.id,{method:'DELETE'});await captures();}});}
 before=data.captures.at(-1)?.id||null;$('more').disabled=data.captures.length<20;
}
$('enabled').onchange=()=>chrome.storage.local.set({urlWatchEnabled:$('enabled').checked});
$('watch-save').onclick=async()=>{await chrome.storage.local.set({watchMode:$('mode').value,allowedDomains:$('domains').value,cooldownMinutes:Math.min(43200,Math.max(0,Number($('cooldown').value)||0))});message('Watcher settings saved.');};
$('check').onclick=()=>watchAction('poll');$('recover').onclick=()=>watchAction('recover');
$('connect').onclick=async()=>{try{const hub=lookOrigin($('hub').value);const granted=await chrome.permissions.request({origins:[new URL(hub).protocol+'//'+new URL(hub).hostname+'/*']});if(!granted)throw Error('Permission was not granted');const r=await fetch(hub+'/api/look-here/info',{credentials:'include',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Connection failed ('+r.status+')');const info=await r.json();if(info.name!=='Look here')throw Error('This is not a Look here hub');const s=await lookSettings();if(hub!==s.hubUrl){await chrome.storage.local.set({urlWatchEnabled:false});await chrome.storage.local.remove(['urlCursor','urlRecoveryCursor']);await chrome.storage.local.set({hubUrl:hub});}const local=chrome.runtime.getManifest().version;$('connection').textContent='Connected: hub '+info.version+', extension '+local+(info.version!==local?'. Update available: replace extension files and Reload in your browser extensions page.':'. Versions match.');await captures();}catch(e){message(e.message);}};
$('defaults').onclick=async()=>{await chrome.storage.local.set({project:$('project').value,thread:$('thread').value});message('Capture defaults saved.');};
$('retention').onclick=async()=>{try{const days=Number($('capture-days').value),url=Number($('url-days').value),draft=Number($('draft-days').value);if(!Number.isInteger(days)||days<0||(days>0&&days<7)||days>3650||!Number.isInteger(url)||url<1||url>30||!Number.isInteger(draft)||draft<0||draft>3650)throw Error('Use valid retention days (captures: 0 or 7–3650; URLs: 1–30).');if(!confirm('Apply retention? Saved data older than these limits can be permanently deleted.'))return;await lookFetch('/api/look-here/capture-retention'+'?days='+days,{method:'PUT'});await lookFetch('/api/look-here/url-retention?days='+url,{method:'PUT'});await chrome.storage.local.set({draftRetentionDays:draft});await drafts();await captures();message('Retention applied.');}catch(e){message(e.message);}};
$('refresh-captures').onclick=()=>captures().catch(e=>message(e.message));$('more').onclick=()=>captures(true).catch(e=>message(e.message));
chrome.storage.onChanged.addListener(()=>renderWatch());
(async()=>{const s=await lookSettings();$('version').textContent='v'+chrome.runtime.getManifest().version;$('hub').value=s.hubUrl;$('mode').value=s.watchMode;$('domains').value=s.allowedDomains;$('cooldown').value=s.cooldownMinutes;$('project').value=s.project;$('thread').value=s.thread;$('draft-days').value=s.draftRetentionDays;const d=await chrome.storage.local.get('urlRetentionDays');$('url-days').value=d.urlRetentionDays||7;await renderWatch();await drafts();try{await captures();const info=await lookFetch('/api/look-here/info');$('connection').textContent='Hub '+info.version+' / extension '+chrome.runtime.getManifest().version;}catch(e){message(e.message);}})();
